// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $analytics from "./routes/analytics.tsx";
import * as $api_calendar from "./routes/api/calendar.ts";
import * as $api_dump from "./routes/api/dump.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $api_logout from "./routes/api/logout.ts";
import * as $api_prompts from "./routes/api/prompts.ts";
import * as $api_register_key from "./routes/api/register-key.ts";
import * as $api_signup from "./routes/api/signup.ts";
import * as $api_verify from "./routes/api/verify.ts";
import * as $api_webhook from "./routes/api/webhook.ts";
import * as $api_wizard from "./routes/api/wizard.ts";
import * as $blog_page_ from "./routes/blog/[page].tsx";
import * as $blog_index from "./routes/blog/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $messages from "./routes/messages.tsx";
import * as $prompts from "./routes/prompts.tsx";
import * as $signup from "./routes/signup.tsx";
import * as $APIKeyForm from "./islands/APIKeyForm.tsx";
import * as $APIKeyManager from "./islands/APIKeyManager.tsx";
import * as $Calendar from "./islands/Calendar.tsx";
import * as $Contacts from "./islands/Contacts.tsx";
import * as $CreateAccount from "./islands/CreateAccount.tsx";
import * as $Dropdown from "./islands/Dropdown.tsx";
import * as $FileUploader from "./islands/FileUploader.tsx";
import * as $Login from "./islands/Login.tsx";
import * as $Logout from "./islands/Logout.tsx";
import * as $MessageManager from "./islands/MessageManager.tsx";
import * as $Messages from "./islands/Messages.tsx";
import * as $Navbar from "./islands/Navbar.tsx";
import * as $Prompts from "./islands/Prompts.tsx";
import * as $Taskbar from "./islands/Taskbar.tsx";
import * as $Wizard from "./islands/Wizard.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/analytics.tsx": $analytics,
    "./routes/api/calendar.ts": $api_calendar,
    "./routes/api/dump.ts": $api_dump,
    "./routes/api/login.ts": $api_login,
    "./routes/api/logout.ts": $api_logout,
    "./routes/api/prompts.ts": $api_prompts,
    "./routes/api/register-key.ts": $api_register_key,
    "./routes/api/signup.ts": $api_signup,
    "./routes/api/verify.ts": $api_verify,
    "./routes/api/webhook.ts": $api_webhook,
    "./routes/api/wizard.ts": $api_wizard,
    "./routes/blog/[page].tsx": $blog_page_,
    "./routes/blog/index.tsx": $blog_index,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/messages.tsx": $messages,
    "./routes/prompts.tsx": $prompts,
    "./routes/signup.tsx": $signup,
  },
  islands: {
    "./islands/APIKeyForm.tsx": $APIKeyForm,
    "./islands/APIKeyManager.tsx": $APIKeyManager,
    "./islands/Calendar.tsx": $Calendar,
    "./islands/Contacts.tsx": $Contacts,
    "./islands/CreateAccount.tsx": $CreateAccount,
    "./islands/Dropdown.tsx": $Dropdown,
    "./islands/FileUploader.tsx": $FileUploader,
    "./islands/Login.tsx": $Login,
    "./islands/Logout.tsx": $Logout,
    "./islands/MessageManager.tsx": $MessageManager,
    "./islands/Messages.tsx": $Messages,
    "./islands/Navbar.tsx": $Navbar,
    "./islands/Prompts.tsx": $Prompts,
    "./islands/Taskbar.tsx": $Taskbar,
    "./islands/Wizard.tsx": $Wizard,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
